package main;

import javax.swing.*;

public class Gui extends javax.swing.JFrame {

    public int choixTaille;
    public Grille grille;
    public boolean choixAleatoire;

    public Gui() {
        this.choixAleatoire = false;
        this.choixTaille = 1;
        this.grille = new Grille(0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new DrawPanel(this);
        Demarrer = new javax.swing.JButton();
        jComboBoxChoixTaille = new javax.swing.JComboBox();
        jLabelChoixTaille = new javax.swing.JLabel();
        jCheckBoxChoixAleatoire = new javax.swing.JCheckBox();
        jLabelChoixCouleur = new javax.swing.JLabel();
        jComboBoxChoixCouleur = new javax.swing.JComboBox();
        ImageIcon imageIcon = new ImageIcon("img/numberlink.png");
        jLabelNumberlink = new javax.swing.JLabel(imageIcon);
        jButtonSolution = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Numberlink");
        setPreferredSize(new java.awt.Dimension(1100, 1300));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 1300));

        jPanel1.setPreferredSize(new java.awt.Dimension(901, 901));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );

        Demarrer.setText("Démarrer partie");
        Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarrerActionPerformed(evt);
            }
        });

        jComboBoxChoixTaille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5x5", "6x6", "7x7", "8x8", "9x9" }));
        jComboBoxChoixTaille.setActionCommand("");
        jComboBoxChoixTaille.setName("choixTaille"); // NOI18N
        jComboBoxChoixTaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixTailleActionPerformed(evt);
            }
        });

        jLabelChoixTaille.setText("Choix de la taille");
        jLabelChoixTaille.setName("choixTailleLabel"); // NOI18N

        jCheckBoxChoixAleatoire.setText("Grillle aléatoire");
        jCheckBoxChoixAleatoire.setName("ifGrilleAleatoire"); // NOI18N
        jCheckBoxChoixAleatoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChoixAleatoireActionPerformed(evt);
            }
        });

        jLabelChoixCouleur.setText("Choix de la couleur");
        jLabelChoixCouleur.setName("choixCouleurLabel"); // NOI18N

        jComboBoxChoixCouleur.setName("choixCouleur"); // NOI18N
        jComboBoxChoixCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixCouleurActionPerformed(evt);
            }
        });

        jButtonSolution.setText("Solution");
        jButtonSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolutionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxChoixAleatoire)
                    .addComponent(Demarrer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelChoixTaille)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxChoixTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelChoixCouleur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxChoixCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSolution)
                        .addGap(49, 49, 49))))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabelNumberlink, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Demarrer)
                        .addGap(40, 40, 40)
                        .addComponent(jCheckBoxChoixAleatoire)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChoixTaille)
                            .addComponent(jComboBoxChoixTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChoixCouleur)
                            .addComponent(jComboBoxChoixCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSolution)))
                .addGap(28, 28, 28)
                .addComponent(jLabelNumberlink, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarrerActionPerformed
        System.out.println("Bouton démarrer");

        // Pour actualiser !
        jPanel1.setVisible(false);
        jPanel1.setVisible(true);
        
        if (choixAleatoire == true) {
            this.grille = new Grille(this.choixTaille);
           //this.grille.aleaGrille(choixTaille, 10000);
        } else {
            switch (this.choixTaille) { // Pas besoin de spécifier input/nomdufichier car pris en compte dans Grille
                case 5:
                    try {
                        this.grille = new Grille("test5x5.csv", 1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
                case 6:
                    try {
                        this.grille = new Grille("test6x6.csv", 1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
                case 7:
                    try {
                        this.grille = new Grille("test7x7.csv", 1);
                    } catch (Exception e) {
                    }
                    break;
                case 8:
                    try {
                        this.grille = new Grille("test8x8.csv", 1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
                case 9:
                    try {
                        this.grille = new Grille("test9x9.csv", 1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
            }
        }

        refreshComboBoxChoixCouleur();
    }//GEN-LAST:event_DemarrerActionPerformed

    private void jComboBoxChoixTailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixTailleActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        Object selected = comboBox.getSelectedItem();
        String temp = selected.toString();
        switch (temp) {
            case "5x5":
                this.choixTaille = 5;
                break;
            case "6x6":
                this.choixTaille = 6;
                break;
            case "7x7":
                this.choixTaille = 7;
                break;
            case "8x8":
                this.choixTaille = 8;
                break;
            case "9x9":
                this.choixTaille = 9;
                break;
        }
        System.out.println(temp);
    }//GEN-LAST:event_jComboBoxChoixTailleActionPerformed

    private void jCheckBoxChoixAleatoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxChoixAleatoireActionPerformed
        AbstractButton abstractButton = (AbstractButton) evt.getSource();
        boolean select = abstractButton.getModel().isSelected();
        this.choixAleatoire = select == true;
        System.out.println(select);
    }//GEN-LAST:event_jCheckBoxChoixAleatoireActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.out.println(evt.getX());
        System.out.println(evt.getY());
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jComboBoxChoixCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixCouleurActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        Object selected = comboBox.getSelectedItem();
        String temp = selected.toString();
    }//GEN-LAST:event_jComboBoxChoixCouleurActionPerformed

    private void jButtonSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolutionActionPerformed
            System.out.println("Bouton solution");

    }//GEN-LAST:event_jButtonSolutionActionPerformed

    /**
     * Actualise le choix des couleurs
     */
    public void refreshComboBoxChoixCouleur() {
        switch (this.grille.nb_color) {
            case 1 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)"}));
            break;
            case 2 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)"}));
            break;
            case 3 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)"}));
            break;
            case 4 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)", "Marron (4)" }));
            break;
            case 5 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)",  "Marron (4)", "Vert (5)"}));
            break;
            case 6 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)" , "Marron (4)", "Vert (5)", "Orange (6)"}));
            break;
            case 7 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)", "Marron (4)", "Vert (5)", "Orange (6)", "Violet(7)"}));
            break;
            case 8 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)", "Marron (4)", "Vert (5)", "Orange (6)", "Violet(7)", "Cyan(8)"}));
            break;
            case 9 :
            jComboBoxChoixCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Blanc (1)", "Rouge (2)", "Rose (3)", "Marron (4)", "Vert (5)", "Orange (6)", "Violet(7)", "Cyan(8)", "Gris(9)"}));
            break;
        }
    }
    
    
    public static void main(String args[]) {
       /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demarrer;
    private javax.swing.JButton jButtonSolution;
    private javax.swing.JCheckBox jCheckBoxChoixAleatoire;
    private javax.swing.JComboBox jComboBoxChoixCouleur;
    private javax.swing.JComboBox jComboBoxChoixTaille;
    private javax.swing.JLabel jLabelChoixCouleur;
    private javax.swing.JLabel jLabelChoixTaille;
    private javax.swing.JLabel jLabelNumberlink;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
